### ISSUE TITLE
Does ConnectionManagerInterface::getConnections have to return an array or ArrayCollection

### ISSUE THREAD

**Issue by armetiz** [Kitano/KitanoConnectionBundle#6]
Meme question pour toutes les méthodes de ConnectionManagerInterface.

**Comment by benjamindulau** [comment]
Good question! Since Doctrine\Common is not related to the ORM, maybe we could use it, ArrayCollection is a very convenient component ;-)

Note that when we will implement caching layer, we will propably use Doctrine\Common anyway!

@Kitano What do you think, should we make use of ArrayCollection in any of our bundles even if Doctrine ORM is not involved ?

**Comment by armetiz** [comment]
+1 For ArrayCollection.

And an other question about getConnectionsXX returns.. Does it return an empty ArrayCollection, or null when there is no result..

**Comment by choomz** [comment]
+1 for ArrayCollection

**Comment by benjamindulau** [comment]
@armetiz I'd say null

**Comment by armetiz** [comment]
ArrayCollection or null is return : https://github.com/Kitano/KitanoConnectionBundle/blob/master/Manager/ConnectionManager.php

**Comment by borisguery** [comment]
I would rather go for an empty `ArrayCollection`, here is why:
- You don't need to do a type check in a foreach

``` php
foreach ($collections as $connection) {
    // will never reach if the collection is empty
}
```

rather than

``` php
if (null !== $collections) {
    foreach ($collections as $connection) {
        // do something
    }
}
```
- ArrayCollection has an utility method to check whether a collection is empty

``` php
$col = new ArrayCollection();
if ($col->isEmpty()) {
   // do something
}
```
- From a design perspective, a collection should always be a collection even if it is empty because it is "typed", `null` seems more appropriate for undefined scalar values.

**Comment by borisguery** [comment]
I would aslo say that we should be tied to the `Collection` interface instead of the `ArrayCollection` to easily change implementation of the Collection if needed.

**Comment by choomz** [comment]
:+1:

**Comment by armetiz** [comment]
Il faut ajouter des Tests pour vérifier le retour des méthodes.
Ca n'a pas été fait et du coups j'ai fait tout le contraire de ce que l'on avait dit.. Shame on me.

**Comment by armetiz** [comment]
Refactoring : 
Utilisation de array uniquement.
Lorsqu'il n'y a pas de resultat, on retourne un array() vide.
